### ISSUE TITLE
Update to JMS Serializer 1.0

### ISSUE THREAD

**Issue by safrazik** [adrotec/breeze.server.php#16]

**Comment by christophercr** [comment]
+1

**Comment by christophercr** [comment]
https://github.com/adrotec/breeze.server.php/pull/17

**Comment by christophercr** [comment]
Hello,

Could you please release a new version for library in order to be able to use it together with the new version of the AdrotecWebApiBundle (containing dependency to the latest JMS serializer version)?

Regards.

**Comment by safrazik** [comment]
Done! - 1.0.5

**Comment by christophercr** [comment]
Thanks a lot!!  ;)
