### ISSUE TITLE
Assitance with install of Emploee Directory

### ISSUE THREAD

**Issue by AugustusM** [adrotec/breeze.server.php#18]
Forgive me if this is the worng place to post this - 

I am having trouble installing the PHP Employee Directory which is located here:  
http://emp-directory.herokuapp.com/

In the directions it says : run composer update from server/standalone directory.

How is that accoplished exactly?  I tried to run it from the url but I get a 404.  Am I supposed to do this at a command line?  I'm installing into a WAMP environment.

Thanks for any help

**Comment by safrazik** [comment]
You should clone/download the source code from https://github.com/adrotec/emp-directory and run the commands locally in a terminal/console. You should also install composer https://getcomposer.org
