### ISSUE TITLE
composer - no matching packages

### ISSUE THREAD

**Issue by slawojstanislawski** [adrotec/breeze.server.php#20]
Upon executing composer update, the following error shows up:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/validator dev-master -> satisfiable by symfony/validator[dev-master].
    - symfony/validator dev-master requires symfony/translation ~2.8|~3.0 -> no matching package found.
  Problem 2
    - Installation request for adrotec/breeze.server.php dev-master -> satisfiable by adrotec/breeze.server.php[dev-master].
    - adrotec/breeze.server.php dev-master requires jms/serializer ~1.0 -> no matching package found.

Perhaps your package should depend on stable releases instead of dev-master? I changed "dev-master" to "@dev" and it temporarily fixes the problem, for the lack of any better/quicker solution, if that can be called so.

It's acutally an issue with the demo: https://github.com/adrotec/breeze.server.php.demo

**Comment by safrazik** [comment]
This issue was moved to adrotec/breeze.server.php.demo#1

**Comment by safrazik** [comment]
the library itself doesn't depend on any development packages. But the demo requires dev of this library for testing. It is not an issue of the library but the demo.
