### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by jasonlfunk** [adrotec/breeze.server.php#22]
Is there a way to do authorization with this as well? I see that there is data validation, but I don't see any authorization. It seems like the Breeze way is to do 'Save Interception'. Is that supported?

**Comment by safrazik** [comment]
We believe that authorization is a different concern, and it depends on the applications. We solved it simply by denying access to certain routes for certain roles. You don't have to depend on the library for this purpose - you shouldn't IMHO. You are not limited to use any of the awesome features provided by Doctrine framework - e.g: lifecycle events. Let's do it the PHP way!
P.S: if you have any better suggestion or solution, please comment. We welcome pull requests too :-)

**Comment by jasonlfunk** [comment]
Lifecycle events on Doctrine should work in my situation. I'll give that a shot. Thanks!
