### ISSUE TITLE
Compatibility with PHP 7

### ISSUE THREAD

**Issue by popovsergiy** [adrotec/breeze.server.php#26]
This is not to `breeze.server.php` but to [your fork of odataphpprod](https://github.com/adrotec/odataphpprod) (that fork not has *Issues* tab).

I get next error when try run code on the PHP 7
`Fatal error: Cannot use ODataProducer\Providers\Metadata\Type\String as String because 'String' is a special class name in vendor\adrotec\odataphpprod\library\ODataProducer\Providers\Metadata\ResourceType.php on line 47`
Can this will be fixed?

**Comment by safrazik** [comment]
This issue was moved to adrotec/odataphpprod#1

**Comment by safrazik** [comment]
I enabled issues on that repo. Please continue discussion at https://github.com/adrotec/odataphpprod/issues/1
